AngelEdu/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace AngelEdu.Models
{
    public class AppUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

AngelEdu/ViewModels/AccountViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AngelEdu.ViewModels
{

    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}

AngelEdu/Controllers/AboutController.cs
using System.Web.Mvc;

namespace AngelEdu.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

AngelEdu/Controllers/BlogController.cs
using System.Web.Mvc;


namespace AngelEdu.Controllers
{
    
    
    public class BlogController : Controller
    {
        
        public ActionResult Home1()
        {
            return View();
        }
    }
}

AngelEdu/Controllers/ContactController.cs
using System.Web.Mvc;

namespace AngelEdu.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

AngelEdu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AngelEdu.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

AngelEdu/Controllers/OtherController.cs
using System.Web.Mvc;


namespace AngelEdu.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult Faq()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

AngelEdu/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace AngelEdu.Controllers
{
    
    
    public class PortfolioController : Controller
    {
        
        public ActionResult TwoColumn()
        {
            return View();
        }
    }
}

AngelEdu/Controllers/ServicesController.cs
using System.Web.Mvc;

namespace AngelEdu.Controllers
{
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

AngelEdu/Views/About/Index.cshtml
@{
    ViewBag.Title = "";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                About
                <small>关于我们</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
            </li>
            <li class="active">关于</li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <img src="http://placehold.it/750x450" class="img-responsive">
    </div>
    <div class="col-md-6">
        <h2>关于我们</h2>
        <p>天使教育是一家由国内外高级专家和学者组成的精英英语教育团队。 主要提供在线英语学习的指导和服务，聘请老师全部为美国本土人士， 为您提供最原汁原味的美国英语。 </p>
    </div>
</div>
<!-- Team Member Profiles -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Team</h2>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-sm-4">
        <img src="http://placehold.it/750x450" class="img-responsive">
        <h3>
            John Smith
            <small>Job Title</small>
        </h3>
        <p>What does this team member do? Keep it short! This is also a great spot for social links!</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li class="tooltip-social facebook-link">
                <a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-profile"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social linkedin-link">
                <a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-profile"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social twitter-link">
                <a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li class="tooltip-social google-plus-link">
                <a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-profile"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
</div>
<!-- Our Customers -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Our Customers</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
        <img src="http://placehold.it/500x300" class="img-responsive img-customer">
    </div>
</div>
</div>

AngelEdu/Views/Blog/Home1.cshtml
@{
    ViewBag.Title = "Blog Home 1";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Blog Home 1
                <small>Blog Homepage</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Blog Home 1</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <h1>
                <a href="@Url.Action("Post")">A Blog Home Template for Bootstrap 3</a>
            </h1>
            <p class="lead">
                by <a href="#">Start Bootstrap</a>
            </p>
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 28, 2013 at 10:00 PM</p>
            <hr>
            <a href="@Url.Action("Post")">
                <img class="img-responsive" src="http://placehold.it/900x300">
            </a>
            <hr>
            <p>This is a very basic starter template for a blog homepage. It makes use of Font Awesome icons that are built into the 'Modern Business' template, and it makes use of the Bootstrap 3 pager at the bottom of the page.</p>
            <a href="@Url.Action("Post")" class="btn btn-primary">Read More <i class="fa fa-angle-right"></i></a>
            <hr>
            <h1>
                <a href="@Url.Action("Post")">Another Blog Post</a>
            </h1>
            <p class="lead">
                by <a href="#">Start Bootstrap</a>
            </p>
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 28, 2013 at 10:45 PM</p>
            <hr>
            <a href="@Url.Action("Post")">
                <img class="img-responsive" src="http://placehold.it/900x300">
            </a>
            <hr>
            <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science...</p>
            <a href="@Url.Action("Post")" class="btn btn-primary">Read More <i class="fa fa-angle-right"></i></a>
            <hr>
            <h1>
                <a href="@Url.Action("Post")">Third Blog Post Entry</a>
            </h1>
            <p class="lead">
                by <a href="#">Start Bootstrap</a>
            </p>
            <hr>
            <p><i class="fa fa-clock-o"></i> Posted on August 28, 2013 at 10:45 PM</p>
            <hr>
            <a href="@Url.Action("Post")">
                <img class="img-responsive" src="http://placehold.it/900x300">
            </a>
            <hr>
            <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science...</p>
            <a href="@Url.Action("Post")" class="btn btn-primary">Read More <i class="fa fa-angle-right"></i></a>
            <hr>
            <ul class="pager">
                <li class="previous">
                    <a href="#">← Older</a>
                </li>
                <li class="next">
                    <a href="#">Newer →</a>
                </li>
            </ul>
        </div>
        <div class="col-lg-4">
            <div class="well">
                <h4>Blog Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </div>
            <!-- /well -->
            <div class="well">
                <h4>Popular Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li>
                                <a href="#dinosaurs">Dinosaurs</a>
                            </li>
                            <li>
                                <a href="#spaceships">Spaceships</a>
                            </li>
                            <li>
                                <a href="#fried-foods">Fried Foods</a>
                            </li>
                            <li>
                                <a href="#wild-animals">Wild Animals</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <li>
                                <a href="#alien-abductions">Alien Abductions</a>
                            </li>
                            <li>
                                <a href="#business-casual">Business Casual</a>
                            </li>
                            <li>
                                <a href="#robots">Robots</a>
                            </li>
                            <li>
                                <a href="#fireworks">Fireworks</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Bootstrap's default well's work great for side widgets! What is a widget anyways...?</p>
            </div>
            <!-- /well -->
        </div>
    </div>
</div>

AngelEdu/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contact <small>We'd Love to Hear From You!</small></h1>
            <ol class="breadcrumb">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="active">Contact</li>
            </ol>
        </div>
        <div class="col-lg-12">
            <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
            <iframe width="100%" scrolling="no" height="400px" frameborder="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed" marginwidth="0" marginheight="0"></iframe>
        </div>
    </div><!-- /.row -->
    <div class="row">
        <div class="col-sm-8">
            <h3>Let's Get In Touch!</h3>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <form action="contact-form-submission.php" method="POST" role="form">
                <div class="row">
                    <div class="form-group col-lg-4">
                        <label for="input1">Name</label>
                        <input type="text" id="input1" class="form-control" name="contact_name">
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="input2">Email Address</label>
                        <input type="email" id="input2" class="form-control" name="contact_email">
                    </div>
                    <div class="form-group col-lg-4">
                        <label for="input3">Phone Number</label>
                        <input type="phone" id="input3" class="form-control" name="contact_phone">
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group col-lg-12">
                        <label for="input4">Message</label>
                        <textarea id="input4" rows="6" class="form-control" name="contact_message"></textarea>
                    </div>
                    <div class="form-group col-lg-12">
                        <input type="hidden" value="contact" name="save">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-4">
            <h3>Modern Business</h3>
            <h4>A Start Bootstrap Template</h4>
            <p>
                5555 44th Street N.<br>
                Bootstrapville, CA 32323<br>
            </p>
            <p><i class="fa fa-phone"></i> <abbr title="Phone">P</abbr>: (555) 984-3600</p>
            <p><i class="fa fa-envelope-o"></i> <abbr title="Email">E</abbr>: <a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a></p>
            <p><i class="fa fa-clock-o"></i> <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
            <ul class="list-unstyled list-inline list-social-icons">
                <li class="tooltip-social facebook-link"><a title="Facebook" data-placement="top" data-toggle="tooltip" href="#facebook-page"><i class="fa fa-facebook-square fa-2x"></i></a></li>
                <li class="tooltip-social linkedin-link"><a title="LinkedIn" data-placement="top" data-toggle="tooltip" href="#linkedin-company-page"><i class="fa fa-linkedin-square fa-2x"></i></a></li>
                <li class="tooltip-social twitter-link"><a title="Twitter" data-placement="top" data-toggle="tooltip" href="#twitter-profile"><i class="fa fa-twitter-square fa-2x"></i></a></li>
                <li class="tooltip-social google-plus-link"><a title="Google+" data-placement="top" data-toggle="tooltip" href="#google-plus-page"><i class="fa fa-google-plus-square fa-2x"></i></a></li>
            </ul>
        </div>
    </div><!-- /.row -->
</div>

AngelEdu/Views/Portfolio/TwoColumn.cshtml
@{
    ViewBag.Title = "Two Column Portfolio";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Two Column Portfolio
                <small>Showcase Your Work</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Two Column Portfolio</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
               @Html.ActionLink("Project Name","SingleItem","Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
        <div class="col-md-6 portfolio-item">
            <a href="@Url.Action("SingleItem","Portfolio")">
                <img src="http://placehold.it/750x450" class="img-responsive">
            </a>
            <h3>
                @Html.ActionLink("Project Name", "SingleItem", "Portfolio")
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>
    </div>
    <hr>
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                <li>
                    <a href="#">«</a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
                <li>
                    <a href="#">2</a>
                </li>
                <li>
                    <a href="#">3</a>
                </li>
                <li>
                    <a href="#">4</a>
                </li>
                <li>
                    <a href="#">5</a>
                </li>
                <li>
                    <a href="#">»</a>
                </li>
            </ul>
        </div>
    </div>
</div>

AngelEdu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modern Business - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @Html.ActionLink("AngelTalk", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="about">
                       @Html.ActionLink("关于", "Index", "About")
                    </li>
                    <li id="services">
                        @Html.ActionLink("课程", "Index", "Services")
                    </li>
                    <li id="contact">
                        @Html.ActionLink("联系我们", "Index", "Contact")
                    </li>
                     <li id="bloghome1">
                        @Html.ActionLink("最新动态", "Home1", "Blog")
                     </li>
                            
                            
                        
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>
</body>
</html>